### PR TITLE
enhance: default fetch depth to 1 if none provided

### PR DESCRIPTION
**Pull request by dtanner**
resolves https://github.com/go-vela/community/issues/444

### CODE REVIEW

**Review by jbrockopp — COMMENTED** [review]
@dtanner thanks for the contribution!

qq: Do we consider this a breaking change?

To be clear, I'm not against this proposed change. I'm asking for my own understanding.

**Comment by dtanner** [comment]
> @dtanner thanks for the contribution!
> 
> qq: Do we consider this a breaking change?
> 
> To be clear, I'm not against this proposed change. I'm asking for my own understanding.

Good question. Technically I think yes it could be considered a breaking change because it's possible someone is relying on it. Realistically I don't think it is though. i.e. I don't know of a situation where you need full depth for a CI/CD build.

**Comment by jbrockopp** [comment]
@dtanner yeah I think that's a fair summary!

I think we'll want to make sure we update the next Vela release notes with this information 👍 

What are your thoughts on additionally setting an explicit default for the `depth` parameter?

https://github.com/go-vela/vela-git/blob/faafd58ff5a2a326000ab3f464f60e3a1ead27a2/cmd/vela-git/main.go#L90-L95

Right now, with the code you added, the plugin implicitly defaults to `1` for the `depth` if none is provided.

What I'm proposing is to keep that code you've added but also set an explicit default of `1` for that parameter:

```go
 &cli.StringFlag{ 
 	EnvVars:  []string{"PARAMETER_DEPTH", "GIT_DEPTH"}, 
 	FilePath: "/vela/parameters/git/depth,/vela/secrets/git/depth", 
 	Name:     "build.depth", 
 	Usage:    "enables fetching the repository with the specified depth",
 	Value:    "1",
 },
```

**Comment by dtanner** [comment]
Sure - defaulting the parameter sounds like a good addition as well.

**Comment by dtanner** [comment]
@jbrockopp check out the latest rev and lemmeno what you think

**Review by wass3r — APPROVED** [review]

**Pull request merged**
